language: node_js
node_js:
  - "7"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project bookstore-c3315 --token 1/ow-KLpADTZYtEwYWyB3oCR-juyISUzZxNeIUpnkl03k